language: ruby
addons:
  postgresql: '9.4'
  chrome: stable
rvm:
  - 2.6.6
cache: bundler
bundler_args: --without development
before_script:
  - wget -N https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - for i in config/*.example; do cp "$i" "${i/.example}"; done
  - bundle exec rake db:setup
  - bundle exec rake db:dev_seed
  - bundle exec rake db:test:prepare
script:
  - "bundle exec rake assets:precompile RAILS_ENV=test > /dev/null 2>&1"
  - "bin/rspec"
env:

notifications:
